In [1]:
import numpy as np

In [5]:
arr=np.array(np.arange(0,25).reshape(5,5))

In [6]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
arr[[0,1]]=arr[[1,0]]

In [8]:
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
np.flip(arr)

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5]])

Convert a row matrix to a column matrix

In [18]:
ar=np.array(np.arange(6).reshape(1,6))

In [19]:
ar

array([[0, 1, 2, 3, 4, 5]])

In [20]:
ar.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [33]:
ar1=np.random.randint(3, size=(5,5))

In [34]:
ar2=np.random.randint(3, size=(5,5))

In [35]:
c=np.equal(ar1,ar2).reshape(5,5)

In [36]:
c

array([[ True, False, False, False, False],
       [False, False,  True,  True, False],
       [False, False, False,  True,  True],
       [False,  True, False, False,  True],
       [ True, False, False, False, False]])

In [38]:
c.astype(int)  

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0]])

In [41]:
d=np.not_equal(ar1,ar2).reshape(5,5)
d

array([[False,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True, False, False],
       [ True, False,  True,  True, False],
       [False,  True,  True,  True,  True]])

In [42]:
d.astype(int)

array([[0, 1, 1, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 1, 1, 1]])

In [45]:
arr=np.random.randint(4,size=(1,10))
arr

array([[3, 0, 1, 1, 3, 1, 3, 0, 0, 3]])

In [60]:
a=np.zeros((10,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.put(arr)

ValueError: setting an array element with a sequence.

In [61]:
a[range(10),arr]=1

In [62]:
a

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [70]:
array=a[np.argmax(a[:,0],axis=0),1]

ValueError: attempt to get argmax of an empty sequence

In [73]:
array=np.argmax(a,axis=1)

In [74]:
array

array([3, 0, 1, 1, 3, 1, 3, 0, 0, 3])

In [75]:
np.random.seed(10)

In [76]:
a=np.random.rand(10,3)

In [77]:
a

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607],
       [0.91777412, 0.71457578, 0.54254437],
       [0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698],
       [0.51313824, 0.65039718, 0.60103895]])

In [78]:
np.find_nearest( a, 0.5 )

AttributeError: module 'numpy' has no attribute 'find_nearest'

In [98]:
c=(np.abs(a - 0.5))

In [99]:
c=c.argmin(axis=1)
c

array([2, 1, 1, 1, 1, 0, 2, 1, 0, 0])

In [104]:
a[np.arange(a.shape[0]),c]

array([0.63364823, 0.49850701, 0.76053071, 0.68535982, 0.51219226,
       0.61252607, 0.54254437, 0.37334076, 0.44183317, 0.51313824])